#!/bin/bash

echo hello world
function interface() {
  type=$1

  case "$type" in
    0) 
      {1..20} | echo "-"
      for ((i=0; i < 20; i++))
      do
        echo "-"
      done
  esac
}
echo "Loading..."
sleep 5

interface 0

echo "helloworld"
